package db_entities;
// Generated 03.05.2017 18:35:45 by Hibernate Tools 4.3.1



/**
 * DescribedObj generated by hbm2java
 */
public class DescribedObj  implements java.io.Serializable {


     private Long id;
     private String name;
     private byte[] foto;
     private String contacts;

    public DescribedObj() {
    }

	
    public DescribedObj(String name, String contacts) {
        this.name = name;
        this.contacts = contacts;
    }
    public DescribedObj(String name, byte[] foto, String contacts) {
       this.name = name;
       this.foto = foto;
       this.contacts = contacts;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getContacts() {
        return this.contacts;
    }
    
    public void setContacts(String contacts) {
        this.contacts = contacts;
    }




}


