package db_entities;
// Generated 28.04.2017 15:25:16 by Hibernate Tools 4.3.1



/**
 * DescribedObj generated by hbm2java
 */
public class DescribedObj  implements java.io.Serializable {


     private Long id;
     private String name;
     private byte[] foto;

    public DescribedObj() {
    }

	
    public DescribedObj(String name) {
        this.name = name;
    }
    public DescribedObj(String name, byte[] foto) {
       this.name = name;
       this.foto = foto;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }




}


