package db_entities;
// Generated 28.04.2017 15:25:16 by Hibernate Tools 4.3.1



/**
 * Description generated by hbm2java
 */
public class Description  implements java.io.Serializable {


     private Long id;
     private long idObject;
     private long idUser;
     private String description;

    public Description() {
    }

    public Description(long idObject, long idUser, String description) {
       this.idObject = idObject;
       this.idUser = idUser;
       this.description = description;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getIdObject() {
        return this.idObject;
    }
    
    public void setIdObject(long idObject) {
        this.idObject = idObject;
    }
    public long getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(long idUser) {
        this.idUser = idUser;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


