package db_entities;
// Generated 05.05.2017 12:56:07 by Hibernate Tools 4.3.1



/**
 * DescribedObj generated by hbm2java
 */
public class DescribedObj  implements java.io.Serializable {


     private Long id;
     private String name;
     private byte[] foto;
     private String contacts;
     private Integer grade;

    public DescribedObj() {
    }

	
    public DescribedObj(String name, String contacts) {
        this.name = name;
        this.contacts = contacts;
    }
    public DescribedObj(String name, byte[] foto, String contacts, Integer grade) {
       this.name = name;
       this.foto = foto;
       this.contacts = contacts;
       this.grade = grade;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getContacts() {
        return this.contacts;
    }
    
    public void setContacts(String contacts) {
        this.contacts = contacts;
    }
    public Integer getGrade() {
        return this.grade;
    }
    
    public void setGrade(Integer grade) {
        this.grade = grade;
    }




}


