package db_entities;
// Generated 08.05.2017 21:44:36 by Hibernate Tools 4.3.1



/**
 * Invitations generated by hbm2java
 */
public class Invitations  implements java.io.Serializable {


     private Integer id;
     private String keyStr;
     private int lvlPermission;

    public Invitations() {
    }

    public Invitations(String keyStr) {
       this.keyStr = keyStr;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getKeyStr() {
        return this.keyStr;
    }
    
    public void setKeyStr(String keyStr) {
        this.keyStr = keyStr;
    }

    public int getLvlPermission() {
        return lvlPermission;
    }

    public void setLvlPermission(int lvlPermission) {
        this.lvlPermission = lvlPermission;
    }
    
    




}


