package db_entities;
// Generated 08.05.2017 12:31:59 by Hibernate Tools 4.3.1



/**
 * Key generated by hbm2java
 */
public class Key  implements java.io.Serializable {


     private long idkeys;

    public Key() {
    }

    public Key(long idkeys) {
       this.idkeys = idkeys;
    }
   
    public long getIdkeys() {
        return this.idkeys;
    }
    
    public void setIdkeys(long idkeys) {
        this.idkeys = idkeys;
    }




}


